---
- name: "updating Ubuntu {{ ansible_distribution_major_version }} (kernel: {{ ansible_kernel }})"
  apt:
    update_cache: yes
    upgrade: dist

- name: check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: reboot server
  shell: sleep 2 && shutdown -r now "Updating kernel for cve-2016-5195"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists

# reconnect to server after update and verify new kernel version is sufficient
## TODO: This does not reliably reconnect to server - is it needed or is it better to verify update in subsequent module
# work-around: run the playbook twice, the second time should show all servers skipped
#- name: waiting for server to come back
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
#  when: reboot_required.stat.exists
#
#- name: get kernel version
#  shell: uname -r
#  register: new_kernel_version
#  changed_when: false
#  when: reboot_required.stat.exists
#
#- name: "new kernel version is {{ new_kernel_version.stdout }}"
#  shell: echo "{{ new_kernel_version.stdout }}"
#  changed_when: false
#  when: reboot_required.stat.exists
